apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agents-app
  labels:
    app: ai-agents-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-agents-app
  template:
    metadata:
      labels:
        app: ai-agents-app
    spec:
      containers:
      - name: ai-agents-app
        image: ai-agents-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3