apiVersion: v1
kind: Service
metadata:
  name: ai-agents-app
  labels:
    app: ai-agents-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ai-agents-app